### ISSUE TITLE
Uncaught TypeError: geolocator.__glcb is not a function

### ISSUE THREAD

**Issue by ZeRego** [onury/geolocator#24] opened 2016-02-12 09:35 UTC
When calling geolocator.locateByIP()  two times I receive the following error in the first call. The second one works correctly.

Uncaught TypeError: geolocator.__glcb is not a function

Here's an example:
https://jsfiddle.net/a95zqjrb/1/

**Comment by onury** [comment] 2016-02-12 13:20
Geolocator only processes a single request at a time.
This is not a bug but rather a missing feature (multiple requests), being addressed in Geolocator version 2 (in development).

The reason for the error you get, is you're making a second call while the first one is still in progress; which removes the first callback on re-initialization.

In order to workaround this; 
1. You should set a timeout for the second call (see [demo](https://jsfiddle.net/a95zqjrb/2/))
2. (Recommended) Execute the second call within the first's callback (see [demo](https://jsfiddle.net/a95zqjrb/3/))

**Comment by onury** [comment] 2016-06-27 00:09
This is resolved in v2 (released).

**Closed by onury** 2016-06-27 00:09 UTC
Labels: feature request, question, v2
